-- Employee

DROP TABLE IF EXISTS T_EMPLOYEES;
  
CREATE TABLE T_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

-- Movies

DROP TABLE IF EXISTS T_MOVIES;
  
CREATE TABLE T_MOVIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  genre VARCHAR(250) DEFAULT NULL
);


-- Player
CREATE TABLE TEAM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE PLAYER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  team_id INT NOT NULL,
  name VARCHAR(250) NOT NULL,
  num INT NOT NULL,
  position VARCHAR(250) NOT NULL,
  
  foreign key (team_id) references TEAM(team_id)
);